### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by hvab** [bem-tools/atom-bem-create#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-bem-create](https://github.com/tadatuta/atom-bem-create) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/hob/.atom/packages/atom-bem-create/lib/atom-bem-create.js:51

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at Object.create (/packages/atom-bem-create/lib/atom-bem-create.js:51:32)
    at /packages/atom-bem-create/lib/atom-bem-create.js:22:29)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:25.4.0 atom-bem-create:create (div.package-detail.panels-item)
     -9:20.4.0 window:toggle-dev-tools (div.package-detail.panels-item)
     -6:43.3.0 atom-bem-create:create (div.tool-panel.tree-view)
```

**Comment by hvab** [comment]
Проще говоря, после обновления атома до 1.17, плагин перестал работать :(
